name: Task
services:

  file-db:
    image: mongo:latest
    volumes:
      - mongodb-data:/var/lib/mongodb/data
    networks:
      - main

  books-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main

  discovery:
    image: consul:1.15.4
    ports:
      - '8500:8500'
    networks:
      - main
      - publish

  api-gateway:
    build: api-gateway
    restart: always
    depends_on:
      - discovery
      - config-server-app
    environment:
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_CONFIG_IMPORT: ${SPRING_CONFIG_IMPORT}
    ports:
      - "8080:8080"
    networks:
      - main
      - publish


  config-server-app:
    build: config-server
    depends_on:
      - discovery
    ports:
      - '8888:8888'
    environment:
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CONFIG_IMPORT}
    networks:
      - main
      - publish

  books-app:
    restart: always
    build: books-app
    depends_on:
      - discovery
      - books-db
      - config-server-app
    environment:
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_DATASOURCE_URL:  ${SPRING_DATASOURCE_URL}
      SPRING_CONFIG_IMPORT: ${SPRING_CONFIG_IMPORT}
    networks:
      - main


  authentication-users:
    build: Authetication-users
    restart: always
    depends_on:
      - discovery
      - books-db
      - config-server-app
    environment:
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_CONFIG_IMPORT: ${SPRING_CONFIG_IMPORT}
    networks:
      - main




  working-file:
    build: working-files
    restart: always
    depends_on:
      - discovery
      - file-db
      - config-server-app
    environment:
      SPRING_CLOUD_CONSUL_HOST: ${SPRING_CLOUD_CONSUL_HOST}
      SPRING_CONFIG_IMPORT: ${SPRING_CONFIG_IMPORT}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
    networks:
      - main





networks:
  main:
    driver: bridge
    internal: true
  publish:
    driver: bridge





volumes:
  postgres-data:
  mongodb-data:


