spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://books-db-svc:5432/InternshipITexus
    username: postgres
    password: pgadmin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  cloud:
    config:
      enabled: false
    consul:
      discovery:
        instance-id: authentication-users-i1
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true