#datasource.url=jdbc:postgresql://localhost:5432/InternshipITexus
#datasource.username=postgres
#datasource.password=pgadmin



spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/InternshipITexus
spring.datasource.username=postgres
spring.datasource.password=pgadmin


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory


spring.mvc.hiddenmethod.filter.enabled=true
