spring:
  kafka:
    bootstrap-servers: kafka-svc:30500
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    consul:
      discovery:
        instance-id: kafka-producer-i1
    config:
      import-check:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true