apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-db-deployment
  labels:
    app: books-db
spec:
  selector:
    matchLabels:
      app: books-db
  template:
    metadata:
      labels:
        app: books-db
    spec:
      containers:
        - name: books-db
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
             - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: pgadmin
            - name: POSTGRES_DB
              value: InternshipITexus
      restartPolicy: Always
      