apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deployment
  labels:
    app: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
      restartPolicy: Always
