apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  labels:
    app: kafka-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: wolfram999/task-kafka-consumer:latest
          ports:
            - containerPort: 8088
              protocol: TCP
          env:
            - name: SPRING_CLOUD_CONSUL_HOST
              value: consul-svc.default.svc.cluster.local
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server@task-config-server-svc.default.svc.cluster.local:8888
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-svc
spec:
  selector:
    app: kafka-consumer
  ports:
    - protocol: TCP
      name: kafka-consumer
      port: 8088
  type: NodePort
